# Generated by Django 2.1.7 on 2019-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='original',
            field=models.URLField(),
        ),
    ]
